# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rawMaterialName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialName', models.CharField(max_length=200, verbose_name='Name of the Material')),
                ('contentSiO2', models.FloatField(default=0)),
                ('contentAl2O3', models.FloatField(default=0)),
            ],
        ),
    ]
