# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BatchCalculator', '0002_auto_20161028_0818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rawMaterialName',
            new_name='rawMaterial',
        ),
    ]
