# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatchCalculator', '0007_auto_20161101_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentSiO2',
            field=models.FloatField(default=0.0, max_length=5, verbose_name='Content SiO<sub>2</sub>'),
        ),
    ]
