# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatchCalculator', '0008_auto_20161101_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='contentK2O',
            field=models.FloatField(default=0.0, max_length=5),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentSiO2',
            field=models.FloatField(default=0.0, max_length=5, verbose_name='Content SiO2'),
        ),
    ]
