# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatchCalculator', '0009_auto_20161101_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentAl2O3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentK2O',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentNa2O',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentSiO2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Content SiO2'),
        ),
    ]
