# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatchCalculator', '0010_auto_20161102_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentAl2O3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentK2O',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentNa2O',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentSiO2',
            field=models.FloatField(default=0.0, verbose_name='Content SiO2'),
        ),
    ]
