# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatchCalculator', '0011_auto_20161112_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='contentBaO',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='contentCaO',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='contentLi2O',
            field=models.FloatField(default=0.0),
        ),
    ]
