# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatchCalculator', '0013_rawmaterial_contentmgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='contentFe2O3',
            field=models.FloatField(default=0.0, verbose_name='Content of Fe<sub>2</sub>O<sub>3</sub>'),
        ),
    ]
