# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatchCalculator', '0014_rawmaterial_contentfe2o3'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='contentB2O3',
            field=models.FloatField(default=0.0, verbose_name='Content of B2O3'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='contentCoO',
            field=models.FloatField(default=0.0, verbose_name='Content of CoO'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='contentCuO',
            field=models.FloatField(default=0.0, verbose_name='Content of CuO'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='contentF',
            field=models.FloatField(default=0.0, verbose_name='Content of F'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='contentMnO',
            field=models.FloatField(default=0.0, verbose_name='Content of MnO'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='contentMoO3',
            field=models.FloatField(default=0.0, verbose_name='Content of MoO3'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='contentNiO',
            field=models.FloatField(default=0.0, verbose_name='Content of NiO'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='contentP2O3',
            field=models.FloatField(default=0.0, verbose_name='Content of P2O5'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='contentSrO',
            field=models.FloatField(default=0.0, verbose_name='Content of SrO'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='contentTiO2',
            field=models.FloatField(default=0.0, verbose_name='Content of TiO2'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='contentZnO',
            field=models.FloatField(default=0.0, verbose_name='Content of ZnO'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='contentZrO2',
            field=models.FloatField(default=0.0, verbose_name='Content of ZrO2'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentAl2O3',
            field=models.FloatField(default=0.0, verbose_name='Content of Al2O3'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentBaO',
            field=models.FloatField(default=0.0, verbose_name='Content of BaO'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentCaO',
            field=models.FloatField(default=0.0, verbose_name='Content of CaO'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentFe2O3',
            field=models.FloatField(default=0.0, verbose_name='Content of Fe2O3'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentK2O',
            field=models.FloatField(default=0.0, verbose_name='Content of K2O'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentLi2O',
            field=models.FloatField(default=0.0, verbose_name='Content of Li2O'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentMgO',
            field=models.FloatField(default=0.0, verbose_name='Content of MgO'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='contentNa2O',
            field=models.FloatField(default=0.0, verbose_name='Content of Na2O'),
        ),
    ]
