# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BatchCalculator', '0015_auto_20161118_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='contentP2O3',
            new_name='contentP2O5',
        ),
    ]
